version: "3.9"

services:
  db:
    build: ./mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  wordpress:
    build: ./wordpress
    depends_on:
      - db
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always

  phpmyadmin:
    build: ./phpmyadmin
    container_name: pma
    links:
      - db
    restart: always
    ports:
      - 8081:80

volumes:
  db_data: { }
  wordpress_data: { }