version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: azerty
      MYSQL_DATABASE: mydb
      MYSQL_USER: root123
      MYSQL_PASSWORD: azerty

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root123
      WORDPRESS_DB_PASSWORD: azerty
      WORDPRESS_DB_NAME: mydb

volumes:
  db_data: { }
  wordpress_data: { }