# Version of this docker-compose.yml
version: "3.9"

# Set the different container to build
services:
  # The MySQL container
  db:
    # Set the MySQL directory on the project
    build: ./mysql
    # Data persistence
    volumes:
      - db_data:/var/lib/mysql
    # Always restart the container if it stops
    restart: always

  # The WordPress container
  wordpress:
    # Set the WordPress directory on the project
    build: ./wordpress
    # The WordPress container depends on the MySQL container named "bd"
    depends_on:
      - db
    # Data persistence
    volumes:
      - wordpress_data:/var/www/html
    # Set the port of the localhost container to 80
    ports:
      - "80:80"
    # Always restart the container if it stops
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:tp-pmn.fr"
      - "traefik.port=2368"
      - "traefik.docker.network=web"
    environment:
      - NODE_ENV=production
      - url=https://tp-pmn.fr

  # The phpmyadmin container
  phpmyadmin:
    # Set the WordPress directory on the project
    build: ./phpmyadmin
    # Link the phpmyadmin service to the MySQL database
    links:
      - db
    # Always restart the container if it stops
    restart: always
    # Set the port of the localhost container to 8081
    ports:
      - "8081:80"

# Volumes are the mechanism for persisting data
volumes:
  # The data persistence for MySQL database
  db_data: { }
  # The data persistence for WordPress
  wordpress_data: { }

networks:
  web:
    external: true