# Select the latest version of phpmyadmin on Docker Hub
FROM phpmyadmin/phpmyadmin

# Mainteners of the project
LABEL MAINTENER="Nicolas-Maroua"

# Set the host for MySQL database
ENV PMA_HOST="db"

# Set the port for MySQL database
ENV PMA_PORT="3306"