# Select the latest version of Wordpress on Docker Hub
FROM wordpress:latest

# Mainteners of the project
LABEL MAINTENER="Nicolas-Maroua"

# Set the MySQL database host
ENV WORDPRESS_DB_HOST="db:3306"

# Set the MySQL database username
ENV WORDPRESS_DB_USER="root123"

# Set the MySQL database password
ENV WORDPRESS_DB_PASSWORD="azerty"

# Set the MySQL database name
ENV WORDPRESS_DB_NAME="mydb"