# Select the version 5.7 of MySQL on Docker Hub
FROM mysql:5.7

# Mainteners of the project
LABEL MAINTENER="Nicolas-Maroua"

# Create a database "mydb"
ENV MYSQL_DATABASE="mydb"

# Set the MySQL root password
ENV MYSQL_ROOT_PASSWORD="azerty"

# Set the MySQL username
ENV MYSQL_USER="root123"

# Set the MySQL password for user "root123"
ENV MYSQL_PASSWORD="azerty"
