# FROM mysql:latest

# LABEL MAINTENER="Nicolas-Maroua"

# # ENV MYSQL_DATABASE mydb
# # ENV MYSQL_ROOT_PASSWORD="azerty"
# # ENV MYSQL_USER="root123"
# # ENV MYSQL_PASSWORD="azerty"

# # EXPOSE 8091
